### ISSUE TITLE
Feature Request - Table Optional View

### ISSUE THREAD

**Issue by mattie-g** [anhthang/raycast-premier-league#1]
Hi, 

If possible instead of seeing the stats on pressing enter on the table view, to see upcoming fixtures (Possibly the last couple of results)? Even as an option.

I know there a separate view for it fixtures but it would be really useful to flick through fixtures on the table.

Thanks!

**Comment by anhthang** [comment]
Hi @mattie-g 

Sorry that I missed your request, but I think the next fixture is already there. You can find it in the end of stats view on pressing enter or hover to the club logo in the end of row

![image](https://github.com/anhthang/raycast-premier-league/assets/10458061/536df578-d8df-4690-8c4f-6b8d722ca802)
![image](https://github.com/anhthang/raycast-premier-league/assets/10458061/a42a0100-f333-4fcf-b4ae-a4076911a816)

Let me know if it's not the thing you want
