### ISSUE TITLE
Incorrect Player Stats

### ISSUE THREAD

**Issue by NewsGuyTor** [anhthang/raycast-premier-league#2]
I just tried the extension and looked up Haaland:
<img width="402" alt="Skjermbilde 2023-05-01 kl  02 15 13" src="https://user-images.githubusercontent.com/19603024/235382927-5dda9301-185a-4bb8-a00b-d9b7cfc6bee7.png">

I don't know where the totally incorrect numbers come from, the browser page does not have those numbers.

**Comment by anhthang** [comment]
Hi @NewsGuyTor 👋 

Thanks for the report, I will check and update after holidays

**Comment by anhthang** [comment]
I've investigated and found that the results vary based on your starting point.

If you navigate from Club > Squad > Player, you'll see current season statistics.
However, if you access player information directly from the Player menu, you'll view their total career statistics, which appear to include data from previous leagues as well.

**Comment by anhthang** [comment]
Fixed https://github.com/anhthang/raycast-premier-league/commit/1c11d6e9044d1edd5486116edaa0282f60c7b13e
